name: main
run-name: Деплой админки

on:
  push

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - run: npm install && npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: build/**
  build-docker:
    runs-on: ubuntu-latest
    needs: [ build-app ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v3
        with:
          name: app-build
          path: build/
      - run: |
          curl -sSL https://get.docker.com/ | sudo sh
          docker build -t ghcr.io/${{ github.repository_owner }}/uda-frontend .
          docker push ghcr.io/${{ github.repository_owner }}/uda-frontend:latest
      - uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: ghcr.io/${{ github.repository_owner }}/uda-frontend
  deploy-app-scp:
    runs-on: ubuntu-latest
    needs: [ build-app ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: app-build
          path: build/
      - run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - run: echo "${{ secrets.OPENVPN_FILE }}" > client.ovpn
      - uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: ./client.ovpn
      - run: mkdir -p ~/.ssh && echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      - run: scp -o StrictHostKeyChecking=no tmp.nginx.conf ${{ secrets.SSH_LOGIN }}:~/frontend/nginx.conf
      - run: scp -o StrictHostKeyChecking=no -r build ${{ secrets.SSH_LOGIN }}:~/frontend/
      - run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_LOGIN }} sudo -i service nginx restart
