name: main
run-name: Основной сценарий

on:
  push

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/uda-frontend
  IMAGE_TAG: latest
  CYPRESS_TEST_HOST: http://localhost:3000/
  PM2_PORT: 3000

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - run: npm install && npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: build/**

  run-e2e-tests:
    runs-on: ubuntu-latest
    needs: [ build-app ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - uses: actions/download-artifact@v3
        with:
          name: app-build
          path: build/
      - run: |
          npm install --only=dev
          npx cypress info || (npx cypress install && npx cypress info)
          pm2 serve dist $PM2_PORT --spa
          npx wait-on $CYPRESS_TEST_HOST --log && npm run test:in

  publish-docker-image:
    runs-on: ubuntu-latest
    needs: [ build-app ]
    if: success() && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v3
        with:
          name: app-build
          path: build/
      - run: |
          sudo apt update -y
          sudo apt install -y apache2-utils
          htpasswd -Bbc .htpasswd ${{ secrets.BA_LOGIN }} ${{ secrets.BA_PASS }}
      - run: |
          curl -sSL https://get.docker.com/ | sudo sh
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME:$IMAGE_TAG

  deploy-docker-image:
    runs-on: ubuntu-latest
    needs: [ publish-docker-image ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa 
            sudo chmod 600 ~/.ssh/id_rsa
            scp -o StrictHostKeyChecking=no .github/workflows/restart-docker.sh ${{ secrets.SSH_LOGIN }}:~/restart-docker.sh
            ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_LOGIN }} "bash restart-docker.sh $IMAGE_NAME:$IMAGE_TAG 80 80"
